host: add deault implementation for system.build.isoImage target (per…
nrdxp/nixflk pull request #102
Opened 2021-01-25 21:50 UTC by blaggacao

… host)

This is a more generic implementation to ISO builds, similar to what nixpkgs/flake.nix does with `lib.nixosSystem` for VMs.

In a follow up PR, I'll implement netboot and sd card flashing (in principle)

see also: https://github.com/numtide/flake-utils/pull/18/commits/d1ff2f04a010c79d4db26a81dc68662200e85862

2021-01-25 21:56 UTC, blaggacao commented
preview idea for possible sd + netboot support: https://github.com/blaggacao/nixflk/pull/1

2021-01-27 16:57 UTC, nrdxp commented
This looks great. Anything else you want to implement, or is it ready for merge?

2021-01-27 17:01 UTC, blaggacao commented
This is ready for merge, going forward you might put a close eye on what would be necessary here: https://github.com/nrdxp/nixflk/pull/102/files#diff-9e2394d5d965447692e8b09d0235b8fdd8426071c2537d0e4a7e4786d9fcf97eR32-R33

Please also build on your machine to check if everything works (it worked over here).

I'm still fighting with sd-images for similar reasons on https://github.com/blaggacao/nixflk/pull/1 (while netboot seems good).

I might open another PR with netboot support, soonish though.

2021-01-27 17:46 UTC, nrdxp commented
I'll give it a test drive and see if everything works out. If so I'll go ahead and merge.

2021-01-27 18:03 UTC, nrdxp requested changes
Basically just wondering if we can break out the logic in lib/default.nix instead of clutter the head of hosts/default.nix. Other than that, everything seems to work wonderfully.

2021-01-27 18:04 UTC, blaggacao commented on hosts/default.nix
> +  libExt = lib.extend (
I think you are right, I just did educated, yet uncritical, copy pasting from `nixpkgs/flake.nix`

2021-01-27 18:04 UTC, blaggacao commented
For future reference / inspiration: https://github.com/nix-community/nixos-generators, specifically: https://github.com/nix-community/nixos-generators/issues/85

2021-01-27 18:08 UTC, nrdxp requested changes
Oh, also please update the README.md to reflect the new changes.

2021-01-28 02:13 UTC, blaggacao commented
Can you review again:

- Readme updated (force push)
- moved to `./lib`

2021-01-28 21:42 UTC, nrdxp requested changes
Sent a PR with some small style fixups to keep the line limit under control. Other than that, this looks ready to merge!

2021-02-02 02:51 UTC, merged