Add NUR support
nrdxp/nixflk pull request #43
Opened 2020-12-25 22:39 UTC by diogox

2020-12-25 23:15 UTC, nrdxp commented
Keep in mind that you can force push to the branch your PR is based off of if you need to rebase or make changes. Making duplicate pull requests isn't ideal. That said, it looks good to me. I'm wondering if we need to specifically declare NUR as an input though, since it is already part of Nix registry.

I'll give it a try and see how it works before merging.

2020-12-25 23:51 UTC, diogox commented
Sorry, I wasn't sure how I could sync a fork with the original, so it was just easier to make a new fork and PR.

Do give it a try. It works for me, but I don't quite understand everything in Nix yet, let alone flakes :smile:

2020-12-26 04:23 UTC, nrdxp requested changes
Overall good job. Just remove the explicit import and it's ready to merge.

2020-12-26 04:23 UTC, nrdxp commented on flake.nix
> +      nur.url = "github:nix-community/NUR";
Remove this line. NUR lives in the flake registry, so we'll just pull it from there.

2020-12-26 12:41 UTC, diogox commented on flake.nix
> +      nur.url = "github:nix-community/NUR";
Done :+1:

2020-12-26 20:08 UTC, diogox commented
Btw, I'm trying to add an `unstable` overlay to my config, but haven't been able to figure out how to do that. Do you know how to do that?

2020-12-27 07:43 UTC, nrdxp approved these changes
Thank you.

2020-12-27 07:43 UTC, merged